apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubecube-monitoring-kubecube.rules
  namespace: kubecube-monitoring
spec:
  groups:
  - name: pod.rules
    rules:
    - record: pod:cpu_usage_percentage
      expr: label_join(100 * irate(container_cpu_usage_seconds_total{container="",namespace!~"kube-system|default|kube-public",pod!=""}[5m]), "target", ".", "namespace", "pod")
      labels:
        cnName: CPU使用率
        unit: "%"
    - record: pod:memory_usage_percentage
      expr: label_join((100 * container_memory_working_set_bytes{container="",namespace!~"kube-system|default|kube-public",pod!=""} / (container_spec_memory_limit_bytes > 0)) or (100 * container_memory_working_set_bytes{container="",namespace!~"kube-system|default|kube-public",pod!=""} / ignoring(container_name, id, image, instance, job, name, namespace, pod) group_left() node_memory_MemTotal_bytes), "target", ".", "namespace", "pod")
      labels:
        cnName: 内存使用率
        unit: "%"
    - record: pod:disk_read_bytes_rate
      expr: label_join(sum by(cluster, container_name, namespace, pod, device) (irate(container_fs_reads_bytes_total{container="",device!="",namespace!~"kube-system|default|kube-public",pod!=""}[5m])), "target", ".", "namespace", "pod")
      labels:
        cnName: 磁盘读字节速率
        unit: "MIB/s"
    - record: pod:disk_write_bytes_rate
      expr: label_join(sum by(cluster, container_name, namespace, pod, device) (irate(container_fs_writes_bytes_total{container="",device!="",namespace!~"kube-system|default|kube-public",pod!=""}[5m])), "target", ".", "namespace", "pod")
      labels:
        cnName: 磁盘写字节速率
        unit: "MIB/s"
    - record: pod:disk_read_operation_rate
      expr: label_join(sum by(cluster, container_name, namespace, pod, device) (irate(container_fs_reads_total{container="",device!="",namespace!~"kube-system|default|kube-public",pod!=""}[5m])), "target", ".", "namespace", "pod")
      labels:
        cnName: 磁盘读操作速率
        unit: "次/s"
    - record: pod:disk_write_operation_rate
      expr: label_join(sum by(cluster, container, namespace, pod, device) (irate(container_fs_writes_total{container="",device!="",namespace!~"kube-system|default|kube-public",pod!=""}[5m])), "target", ".", "namespace", "pod")
      labels:
        cnName: 磁盘写操作速率
        unit: "次/s"
    - record: pod:network_receive_packets_rate
      expr: label_join(sum by(cluster, namespace, pod, interface) (irate(container_network_receive_packets_total{container="POD",interface!~"bond.*|tunl.*|lo.*|cali.*",namespace!~"kube-system|default|kube-public"}[5m])), "target", ".", "namespace", "pod")
      labels:
        cnName: 网络收包速率
        unit: "pps"
    - record: pod:network_transmit_packets_rate
      expr: label_join(sum by(cluster, namespace, pod, interface) (irate(container_network_transmit_packets_total{container="POD",interface!~"bond.*|tunl.*|lo.*|cali.*",namespace!~"kube-system|default|kube-public"}[5m])), "target", ".", "namespace", "pod")
      labels:
        cnName: 网络发包速率
        unit: "pps"
    - record: pod:network_receive_bytes_rate
      expr: label_join(sum by(cluster, namespace, pod, interface) (irate(container_network_receive_bytes_total{container="POD",interface!~"bond.*|tunl.*|lo.*|cali.*",namespace!~"kube-system|default|kube-public"}[5m])), "target", ".", "namespace", "pod")
      labels:
        cnName: 网络收字节速率
        unit: "MIB/s"
    - record: pod:network_transmit_bytes_rate
      expr: label_join(sum by(cluster, cluster, namespace, pod, interface) (irate(container_network_transmit_bytes_total{container="POD",interface!~"bond.*|tunl.*|lo.*|cali.*",namespace!~"kube-system|default|kube-public"}[5m])), "target", ".", "namespace", "pod")
      labels:
        cnName: 网络发字节速率
        unit: "MIB/s"
  - name: container.rules
    rules:
    - record: container:cpu_usage_percentage
      expr: label_join(100 * irate(container_cpu_usage_seconds_total{container!~"|POD",namespace!~"kube-system|default|kube-public"}[5m]), "target", ".", "namespace", "pod", "container")
      labels:
        cnName: CPU使用率
        unit: "%"
    - record: container:memory_usage_percentage
      expr: (100 * container_memory_working_set_bytes{container!~"|POD",namespace!~"kube-system|default|kube-public"} / (container_spec_memory_limit_bytes > 0)) or (100 * container_memory_working_set_bytes{container!~"|POD",namespace!~"kube-system|default|kube-public"} / ignoring(container, id, image, instance, job, name, namespace, pod) group_left() node_memory_MemTotal_bytes)
      labels:
        cnName: 内存使用率
        unit: "%"
    - record: container:disk_read_bytes_rate
      expr: label_join(sum by(cluster, container, namespace, pod, device, node) (irate(container_disk_read_bytes_total[5m])) / count by(cluster, container, namespace, pod, device, node) (container_disk_read_bytes_total), "target", ".", "namespace", "pod", "container_name")
      labels:
        cnName: 磁盘读字节速率
        unit: "MIB/s"
    - record: container:disk_write_bytes_rate
      expr: label_join(sum by(cluster, container, namespace, pod_name, device, node) (irate(container_disk_write_bytes_total[5m])) / count by(cluster, container, namespace, pod, device, node) (container_disk_write_bytes_total), "target", ".", "namespace", "pod", "container")
      labels:
        cnName: 磁盘写字节速率
        unit: "MIB/s"
    - record: container:disk_write_operation_rate
      expr: label_join(sum by(cluster, container, namespace, pod, device, node) (irate(container_disk_write_completed_total[5m])) / count by(cluster, container, namespace, pod, device, node) (container_disk_write_completed_total), "target", ".", "namespace", "pod", "container")
      labels:
        cnName: 磁盘写操作速率
        unit: "次/s"
    - record: container:disk_read_operation_rate
      expr: label_join(sum by(cluster, container, namespace, pod, device, node) (irate(container_disk_read_completed_total[5m])) / count by(cluster, container, namespace, pod, device, node) (container_disk_read_completed_total), "target", ".", "namespace", "pod", "container")
      labels:
        cnName: 磁盘读操作速率
        unit: "次/s"
  - name: workload.rules
    rules:
    - expr: label_join(kube_deployment_status_replicas_available, "target", ".", "namespace", "deployment") or label_join(kube_statefulset_status_replicas_current, "target", ".", "namespace", "statefulset")
      record: workload:current_replicas
      labels:
        cnName: 当前副本数
  - name: persistentvolumeclaim.rules
    rules:
    - expr: label_join((avg by(cluster, namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes/ kubelet_volume_stats_capacity_bytes * 100) or avg by(cluster, namespace,persistentvolumeclaim) (kube_persistentvolumeclaim_info * on(cluster, volumename) group_left() avg by(cluster,  volumename) (label_replace(100 * pv_used / pv_size, "volumename", "$1", "pvcname", "(.*)")))),"target", ".", "namespace", "persistentvolumeclaim")
      record: storage:persistentvolumecalim_used_percentage
      labels:
        cnName: 水位
        unit: "%"
  - name: cephfsPersistentvolumeclaim.rules
    rules:
    - expr: label_join((avg by(cluster, namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes/ kubelet_volume_stats_capacity_bytes * 100) or avg by(cluster, namespace,persistentvolumeclaim) (kube_persistentvolumeclaim_info * on(cluster, volumename) group_left() avg by(cluster,  volumename) (label_replace(100 * pv_used / pv_size, "volumename", "$1", "pvcname", "(.*)")))),"target", ".", "namespace", "persistentvolumeclaim")
      record: storage:persistentvolumecalim_used_percentage
      labels:
        cnName: 水位
        unit: "%"
    - record: storage:persistentvolumecalim_read_operation_rate
      expr: label_join(avg by(cluster, namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info, "persistentvolume", "$1", "volumename", "(.*)") * on(cluster, cluster, persistentvolume) group_left(volumename) label_replace(irate(rlat_count[2m]), "persistentvolume", "$1", "pvcname", "(.*)")), "target", ".", "namespace", "persistentvolumeclaim")
      labels:
        cnName: 读操作速率
        unit: "次/s"
    - record: storage:persistentvolumecalim_write_operation_rate
      expr: label_join(avg by(cluster, namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info, "persistentvolume", "$1", "volumename", "(.*)") * on(cluster, cluster_name, persistentvolume) group_left(volumename) label_replace(irate(wrlat_count[2m]), "persistentvolume", "$1", "pvcname", "(.*)")), "target", ".", "namespace", "persistentvolumeclaim")
      labels:
        cnName: 写操作速率
        unit: "次/s"
    - record: storage:persistentvolumecalim_write_bytes_rate
      expr: label_join(avg by(cluster, namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info, "persistentvolume", "$1", "volumename", "(.*)") * on(cluster, cluster_name, persistentvolume) group_left(volumename) label_replace(irate(w_bytes[2m]), "persistentvolume", "$1", "pvcname", "(.*)")), "target", ".", "namespace", "persistentvolumeclaim")
      labels:
        cnName: 写字节速率
        unit: "B/s"
    - record: storage:persistentvolumecalim_write_lantency
      expr: label_join(avg by(cluster, namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info, "persistentvolume", "$1", "volumename", "(.*)") * on(cluster, cluster_name, persistentvolume) group_left(volumename) label_replace(wrlat_lat, "persistentvolume", "$1", "pvcname", "(.*)")), "target", ".", "namespace", "persistentvolumeclaim")
      labels:
        cnName: 写操作延时
        unit: "ms"
    - record: storage:persistentvolumecalim_read_lantency
      expr: label_join(avg by(cluster, namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info, "persistentvolume", "$1", "volumename", "(.*)") * on(cluster, cluster_name, persistentvolume) group_left(volumename) label_replace(rlat_lat, "persistentvolume", "$1", "pvcname", "(.*)")), "target", ".", "namespace", "persistentvolumeclaim")
      labels:
        cnName: 读操作延时
        unit: "ms"
  - name: namespace.rules
    rules:
    - record: namespace:pod_count
      expr: count by(namespace, cluster) (kube_pod_info{namespace!~"kube-system|default|kube-public"})
      labels:
        cnName: 未就绪节点数